# Generated by Django 5.2.3 on 2025-07-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Calafate Austral', max_length=200, verbose_name='Nombre de la tienda')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/', verbose_name='Logo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email de contacto')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('politica_envio', models.TextField(blank=True, null=True, verbose_name='Política de Envíos')),
                ('politica_devolucion', models.TextField(blank=True, null=True, verbose_name='Política de Devoluciones')),
                ('politica_privacidad', models.TextField(blank=True, null=True, verbose_name='Política de Privacidad')),
                ('terminos', models.TextField(blank=True, null=True, verbose_name='Términos y Condiciones')),
                ('metodo_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='Método de Pago Principal')),
                ('credencial_pago', models.CharField(blank=True, max_length=255, null=True, verbose_name='Credencial de Pago')),
                ('servicio_envio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Servicio de Envío')),
                ('webhook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Webhook/Integración')),
                ('color_primario', models.CharField(blank=True, max_length=7, null=True, verbose_name='Color Primario (hex)')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de la Tienda',
                'verbose_name_plural': 'Configuración de la Tienda',
            },
        ),
    ]
